# Porta do servidor Backend
server.port=8080

# Configuração da conexão com o H2 Database
spring.datasource.url=jdbc:h2:mem:recipebookdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Criação do banco do zero ao iniciar e apaga ao fechar
spring.jpa.hibernate.ddl-auto=create-drop

# Exibição de SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto explícito do H2 (evita warnings no console)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativação do Console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Inicialização de dados
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true