# Porta do servidor Backend
server.port=8080

# Configuração da conexão com o H2 Database
spring.datasource.url=jdbc:h2:mem:recipebookdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Estratégia de criação das tabelas (cria/atualiza baseado nas entidades Java)
spring.jpa.hibernate.ddl-auto=update

# Exibe os comandos SQL gerados no console (bom para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ativa o Console Web do H2 para você conseguir visualizar as tabelas pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true